volumes:
  rabbitmq_data:

services:
  # ####################################
  # # Atomic Microservice: Notifications
  # ####################################
  # notifications:
  #   build:
  #     context: ./services/notifications
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   env_file:
  #     - 'dev.env'
  #   environment:
  #     PYTHONUNBUFFERED: 1

  ####################################
  # Microservice: Users
  ####################################
  users:
    build:
      context: ../services/users
      dockerfile: Dockerfile
    restart: always
    env_file:
      - "dev.env"
    ports:
      - "33000:5000"
    environment:
      PYTHONUNBUFFERED: 1
  ####################################
  # Composite Microservice: Booking_Management
  ####################################
  bookings:
    build:
      context: ../services/booking_management
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - "dev.env"
    ports:
      - "30000:5000"
    environment:
      PYTHONUNBUFFERED: 1
  ####################################
  # Atomic Microservice: Hotels
  ####################################
  hotels:
    build:
      context: ./services/hotels
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - 'dev.env'
    # ports:
    #   - "31000:5000"
  ####################################
  # Atomic Microservice: Payment
  ####################################
  payment:
    build:
      context: ../services/payment
      dockerfile: Dockerfile
    restart: always
    env_file:
      - "dev.env"
    ports:
      - "31000:5000"

  ####################################
  # Atomic Microservice: Hotels
  ####################################
  hotels:
    build:
      context: ../services/hotels
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - "dev.env"
    ports:
      - "32000:5000"

  ####################################
  # Atomic Microservice: Users
  ####################################
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    restart: always
    env_file:
      - 'dev.env'
    # ports:
    #   - "31000:5000"
  ####################################
  # RabbitMQ: The messaging broker
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  ###################################
  # nginx: API Gateway
  ###################################
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - hotels
      - bookings
      - payment
      - notifications
      - users
    env_file:
      - "dev.env"
    ports:
      - "8080:80"
