spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hotel.book.updates@gmail.com
spring.mail.password=qoeb plzb rldh ocvl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# RabbitMQ connection properties
# spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# spring.rabbitmq.listener.simple.auto-startup=true
# spring.rabbitmq.virtual-host=/
# server.port=8081

# server.address=http://localhost:8080
# server.port=8080
